debug = true

[Postgres]
database = ""
host = "127.0.0.1"
password = ""
port = "5432"
user = ""

[Redis]
database = 0
host = "127.0.0.1"
password = ""
port = "6379"

[Http]
enableApi = true
host = "0.0.0.0"
port = "8000"

[JWT]
lifeTime = 24
secret = ""

[Logger]
logsPath = "./"

[Logger.RestApi]
compress = true # сжимать старые логи
maxSize = 100 # максимальный размер лога в Мб
maxAge = 30 # срок хранения старых логов в днях
maxBackups = 10 # максимальное кол-во файлов со старыми логами
