debug = true

[Postgres]
database = ""
host = "127.0.0.1"
password = ""
port = "5432"
user = ""

[Redis]
database = 0
host = "127.0.0.1"
password = ""
port = "6379"

[Http]
enableApi = true
host = "0.0.0.0"
port = "8000"

[JWT]
lifeTime = 24
secret = ""

[Logger]
logsPath = "./"

[Logger.RestApi]
compress = true # compress old logs
maxSize = 100 # maximum log size in MB
maxAge = 30 # storage period for old logs in days
maxBackups = 10 # maximum number of files with old logs
